// This file is auto-generated by @hey-api/openapi-ts

export enum AppliesTo {
    PATH_AND_QUERY = 'PathAndQuery',
    PATH = 'Path',
    HOST = 'Host',
    QUERY = 'Query'
}

export type AuthRule = {
    name: string;
    pattern: string;
    enabled: boolean;
    appliesTo: AppliesTo;
};

export type AuthRules = {
    ipWhitelist?: Array<string> | null;
    headers?: Array<HeaderDetail> | null;
    rules?: Array<AuthRule> | null;
};

export type HeaderDetail = {
    header: string;
    value?: string | null;
};

export type MyaRpEnabled = {
    enabled: boolean;
    code?: string | null;
};

export type EnabledData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/myarequestprotectumbracoadmin/api/v1/enbaled';
};

export type EnabledErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type EnabledResponses = {
    /**
     * OK
     */
    200: MyaRpEnabled;
};

export type EnabledResponse = EnabledResponses[keyof EnabledResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/myarequestprotectumbracoadmin/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type GetProtectRulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/myarequestprotectumbracoadmin/api/v1/protectrules';
};

export type GetProtectRulesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetProtectRulesResponses = {
    /**
     * OK
     */
    200: AuthRules;
};

export type GetProtectRulesResponse = GetProtectRulesResponses[keyof GetProtectRulesResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44334' | (string & {});
};